Page pour "Mon compte"
anct-cnum/portail-backoffice pull request #160
Opened 2021-06-07 14:16 UTC by Ornella452

2021-06-08 18:23 UTC, squirrion commented on src/services/structure.service.js
> +    headers: obj,
@Ornella452 tu peux mettre directement le contenu de Obj dans headers (simplification)

2021-06-08 18:25 UTC, squirrion commented on src/actions/structure.actions.js
> +  console.log('info:', info);
@Ornella452 Tu peux virer le console.log

2021-06-08 18:29 UTC, squirrion commented on src/reducers/structureReducer.js
> +        flashMessage: false
@Ornella452 humm ok, c'est pour afficher un message flash après patch. Il faut que tu le passes à flashMessage: true dans le success et le failure en-dessous (message affiché après clic patch)

2021-06-08 18:35 UTC, squirrion commented on src/reducers/structureReducer.js
> +        error: action.error
@Ornella452 Tu peux renommer en patchError par exemple (pour éviter conflit avec error utilisé dans d'autres types au-dessus : 
'patchError: action.error'

2021-06-08 18:43 UTC, squirrion commented
@Ornella452 Pour utiliser le message flash là où tu veux l'afficher (surement dans le fichier monCompte.js):
1. Import : `import FlashMessage from 'react-flash-message';`
2. Tu créé une variable pour récupérer le state structure patchError défini dans le reducer.
3. Tu déclares le flash message dans ce genre là à afficher si flashMessage === true (défini dans le reducer)
      <FlashMessage duration={10000}>
        { (error === undefined || error === false) &&
        <p className="rf-label flashBag">
          Mise à jour OK
        </p>
        }
        { (error !== undefined && error !== false) &&
        <p className="rf-label flashBag labelError">
          Mise à jour KO
        </p>
        }
      </FlashMessage>

2021-06-09 08:50 UTC, squirrion commented on src/reducers/structureReducer.js
> +        structure: action.structure
@Ornella452 ajoutes flashMessage: true aussi ici car le message flash pourra être affiché si success ou failure

2021-06-09 08:52 UTC, squirrion commented on src/components/connected/structure/MonCompte.js
> +  const error = useSelector(state => state.patchError);
@Ornella452 Humm je pense que c'est plutôt : 
`const error = useSelector(state => state.structure?.patchError);` (on est dans le reducer structure)

2021-06-09 08:54 UTC, squirrion commented on src/components/connected/structure/MonCompte.js
> +  const [message, setMessage] = useState(false);
@Ornella452 Normalement, pas besoin. tu peux supprimer. On utilisera du coup le flashMessage à true ou false

2021-06-09 08:54 UTC, squirrion commented on src/components/connected/structure/MonCompte.js
> +    setMessage(true);
@Ornella452 tu peux supprimer aussi du coup

2021-06-09 08:55 UTC, squirrion commented on src/components/connected/structure/MonCompte.js
> +        {message === true ?
au lieu de message utiliser structure?.flashMessage === true (celui qui est maj dans le reducer)

2021-06-09 08:56 UTC, squirrion commented on src/components/connected/structure/MonCompte.js
> +                Mise à jour KO
@Ornella452 Détail : peut etre mettre une phrase du style : La mise à jour a échoué, veuillez réessayer plus tard

2021-06-09 08:57 UTC, squirrion commented on src/components/connected/structure/MonCompte.js
> +                Mise à jour OK
@Ornella452 Détail : pour le libellé, on pourra mettre : La mise à jour a été effectuée avec succès

2021-06-09 09:07 UTC, Ornella452 commented on src/components/connected/structure/MonCompte.js
> +    setMessage(true);
@squirrion En faite j'ai rajouter ce petit système car quand je click sur "Mon compte" dans le menu , le message appairer directement alors qu'il doit normalement apparaitre après avoir fait valider avec le formulaire

2021-06-09 09:09 UTC, Ornella452 commented on src/components/connected/structure/MonCompte.js
> +    setMessage(true);
Ha c'est bon , ton commentaire suivant règle le soucis ^^

2021-06-09 09:19 UTC, Ornella452 commented on src/components/connected/structure/MonCompte.js
> +        {message === true ?
Merci pour cette solution

2021-06-09 09:58 UTC, loicguillois requested changes

2021-06-09 09:58 UTC, loicguillois commented on src/components/connected/structure/InfoAModifier.js
> +      <button style={{ float: 'right' }} className="rf-btn" onClick={onClick}>Valider</button>
évites les callbacks qui n'apporte aucune information, ici on serait plutôt sur `updateInfo` à la place de `onClick`

2021-06-09 09:58 UTC, loicguillois commented on src/components/connected/structure/MonCompte.js
> +            <InfoAModifier structure={structure?.structure?.contact} infoForm={infoForm} setInfoForm={setInfoForm} onClick={patch}/>
tu dois éviter d'utiliser des props: c'est l'objectif d'utiliser Redux. inutile d'avoir `infoForm`, `setInfoForm`, `onClick` ici ça doit être géré par le composant `InfoAModifier`

2021-06-09 09:58 UTC, loicguillois commented on src/components/connected/structure/InfoAModifier.js
> +function InfoAModifier({ infoForm, setInfoForm, onClick }) {
Le nom de ton composant est trop générique et n'apporte aucune information. Appelles le plutôt `StructureContactForm`

2021-06-09 09:58 UTC, loicguillois commented on src/components/connected/structure/InfoAModifier.js
> +        <input className="rf-input" type="text" id="text-input-text" name="nom" placeholder={infoForm?.nom} onChange={handleForm} />
le `placeholder` ne doit être utilisé que pour donner un exemple de saisie. Ici c'est une valeur, donc `value` (pareil pour les autres)

2021-06-09 09:58 UTC, loicguillois commented on src/components/connected/structure/index.js
> +      window.$crisp.push(['safe', 'true']);
à supprimer si ça ne corrige pas le problème

2021-06-09 10:32 UTC, Ornella452 commented on src/components/connected/structure/MonCompte.js
> +            <InfoAModifier structure={structure?.structure?.contact} infoForm={infoForm} setInfoForm={setInfoForm} onClick={patch}/>
@loicguillois si je comprend bien toute mes manipulations que j'ai fait dans MonCompte.js au lieux d'utiliser la méthode des Props , je fait directe dans StructureContactForm.js  (InfoAModifier) ?!

2021-06-09 10:51 UTC, Ornella452 commented on src/components/connected/structure/InfoAModifier.js
> +        <input className="rf-input" type="text" id="text-input-text" name="nom" placeholder={infoForm?.nom} onChange={handleForm} />
de base je voulais mettre value mais je suis bloquer , je n'arrive pas à saisir dans l'input du coup c'est pour ça que j'ai mis "placeholder" : /

2021-06-09 12:43 UTC, loicguillois commented on src/components/connected/structure/MonCompte.js
> +            <InfoAModifier structure={structure?.structure?.contact} infoForm={infoForm} setInfoForm={setInfoForm} onClick={patch}/>
oui

2021-06-09 12:44 UTC, loicguillois commented on src/components/connected/structure/InfoAModifier.js
> +        <input className="rf-input" type="text" id="text-input-text" name="nom" placeholder={infoForm?.nom} onChange={handleForm} />
ça marchait pas sûrement parce que infoForm était une props. il faut que ce soit une valeur du state

2021-06-09 12:55 UTC, Ornella452 commented on src/components/connected/structure/InfoAModifier.js
> +        <input className="rf-input" type="text" id="text-input-text" name="nom" placeholder={infoForm?.nom} onChange={handleForm} />
toujours pareil , je peux rien changer dans l'input

2021-06-09 13:54 UTC, loicguillois approved these changes

2021-06-09 13:58 UTC, merged