Info de L'idPG dans le dispatch
anct-cnum/portail-backoffice pull request #164
Opened 2021-06-10 11:37 UTC by Ornella452

2021-06-10 12:04 UTC, loicguillois commented on src/services/structure.service.js
> +function patch({ id, idPG, contact }) {
tu peux retirer l'id vu que tu ne l'utilises pas

2021-06-10 12:07 UTC, Ornella452 commented on src/services/structure.service.js
> +function patch({ id, idPG, contact }) {
pour l'id , j'en ai besoin car c'est un PATCH
ligne 67 dans structure.service.js 
 `return fetch(`${apiUrlRoot}/structures/${id}`, requestOptions).then(handleResponse);`

2021-06-10 12:09 UTC, squirrion commented on src/components/connected/structure/StructureContactForm.js
> +    dispatch(structureActions.patch({ id: structure?.structure?._id, idPG: structure?.structure?.idPG, contact: infoForm }));
@Ornella452 A confirmer avec @loicguillois mais j'aurai plutôt récupéré le idPG côté API / hook

2021-06-10 13:20 UTC, Ornella452 commented on src/components/connected/structure/StructureContactForm.js
> +    dispatch(structureActions.patch({ id: structure?.structure?._id, idPG: structure?.structure?.idPG, contact: infoForm }));
oui c'est une autre option possible , @loicguillois je prend l'option suggérer par Sébastien ou je laisse comme ça ?!

2021-06-10 18:37 UTC, squirrion requested changes
@Ornella452 Oui à confirmer si on supprime cette PR ou non (on va chercher directement idPg côté API)

2021-06-11 07:35 UTC, loicguillois commented on src/components/connected/structure/StructureContactForm.js
> +    dispatch(structureActions.patch({ id: structure?.structure?._id, idPG: structure?.structure?.idPG, contact: infoForm }));
oui c'est mieux

2021-06-11 07:56 UTC, Ornella452 commented on src/components/connected/structure/StructureContactForm.js
> +    dispatch(structureActions.patch({ id: structure?.structure?._id, idPG: structure?.structure?.idPG, contact: infoForm }));
d'accord, je vais du coup simplement fermé cette PR et faire directement coter API  ( après les demandes de support en cours)

2021-06-11 14:08 UTC, closed without merging