[espace sa] ajouter une colonne avec l'information "candidat déjà recruté" lorsque le candidat est recruté.
anct-cnum/portail-backoffice pull request #177
Opened 2021-06-23 10:31 UTC by Ornella452

…ue le candidat est recruté.

2021-06-23 12:09 UTC, MorganP-projects commented on src/components/connected/structure/Conseiller.js
> +    label: 'Candidat recruté'
Tu peux remettre "Candidature validée" ici :)

2021-06-23 12:15 UTC, Ornella452 commented on src/components/connected/structure/Conseiller.js
> +    label: 'Candidat recruté'
yes c'est fait avec le 2 èmes commit :)

2021-06-23 12:18 UTC, squirrion commented on src/components/connected/structure/Conseiller.js
> +          <p className="rf-btn rf-fi-eye-line rf-btn--icon-left" style={{ background: '#383838', opacity: '0.33' }}>
@Ornella452 Je ne sais pas si on peut passer le link en disabled avec la condition? 
un genre de `disabled={miseEnRelation.statut === 'finalisee' ? true : false}` uniquement - à tester par rapport au Design System si ca le fait ou non

2021-06-23 12:41 UTC, Ornella452 commented on src/components/connected/structure/Conseiller.js
> +          <p className="rf-btn rf-fi-eye-line rf-btn--icon-left" style={{ background: '#383838', opacity: '0.33' }}>
ok je test

2021-06-23 12:49 UTC, Ornella452 commented on src/components/connected/structure/Conseiller.js
> +          <p className="rf-btn rf-fi-eye-line rf-btn--icon-left" style={{ background: '#383838', opacity: '0.33' }}>
non ça le fait pas :/

2021-06-23 12:55 UTC, squirrion commented on src/components/connected/structure/Conseiller.js
> +          <p className="rf-btn rf-fi-eye-line rf-btn--icon-left" style={{ background: '#383838', opacity: '0.33' }}>
Oki dommage

2021-06-23 12:56 UTC, squirrion approved these changes

2021-06-24 08:49 UTC, loicguillois commented on src/components/connected/structure/Conseiller.js
> +      <td>{miseEnRelation.conseillerObj.idPG === conseillerCandidat.conseillerObj.idPG ?
je ne comprend pas cette comparaison

2021-06-24 08:49 UTC, loicguillois requested changes
l'utilisation de ma miseEnRelation et du conseillerCandidat est complètement flou

2021-06-24 09:19 UTC, squirrion commented on src/components/connected/structure/Conseiller.js
> +      <td>{miseEnRelation.conseillerObj.idPG === conseillerCandidat.conseillerObj.idPG ?
Effectivement, sauf erreur j'aurai pensé plutôt à une autre info remontée par l'API sur les mises en relation récupérées (avec par exemple une donnée calculée remontée alreadyFinalisee à false/true si le conseiller a une mise en relation statut finalisee avec une autre structure)

2021-06-24 10:05 UTC, squirrion commented on src/components/connected/structure/Conseiller.js
> +        {miseEnRelation.statut === 'finalisee' ?
@Ornella452 A confirmer mais ca me parait bizarre : on grise le bouton si finalisee donc la structure qui a finalisee son propre recrutement ne peut plus cliquer sur les détails. Ce comportement de grisage ce n'est pas pour les autres structures ? (le statut de la sa mise en relation n'est pas finalisee mais est finalisée dans une autre mise en relation d'une autre structure.
Ou j'ai mal compris

2021-06-24 10:08 UTC, Ornella452 commented on src/components/connected/structure/Conseiller.js
> +        {miseEnRelation.statut === 'finalisee' ?
apparemment c'est 2 ticket à pars , mais oui de ce que j'ai compris du ticket initiale c'est ça :/ ... ( cc : @loicguillois )

2021-06-24 10:13 UTC, MorganP-projects commented on src/components/connected/structure/Conseiller.js
> +        {miseEnRelation.statut === 'finalisee' ?
Je pense que le ticket a été mal formulé...
Parce que je comprend le besoin comme Seb. 
On va avoir des retours de structure mécontente de ne pas avoir les données deux leurs employés...

2021-06-24 10:16 UTC, loicguillois commented on src/components/connected/structure/Conseiller.js
> +        {miseEnRelation.statut === 'finalisee' ?
je ne vois pas quel ticket trello correspond à cette PR... encore une fois

2021-06-24 10:22 UTC, MorganP-projects commented on src/components/connected/structure/Conseiller.js
> +        {miseEnRelation.statut === 'finalisee' ?
Celui-ci :
https://trello.com/c/qmDPHxXx/629-espace-sa-ajouter-une-colonne-avec-linformation-candidat-deja-recrut%C3%A9-lorsque-le-candidat-est-recrut%C3%A9-complexit%C3%A9-3

Du coup juste grisé pour la structure qui à la mise en relation "finalisee" ça ne colle pas

2021-06-24 16:44 UTC, closed without merging