WIP : Possibilité de laisser l'utilisateur d'une SA changer son email de connexion dans son espace SA
anct-cnum/portail-backoffice pull request #179
Opened 2021-06-24 17:33 UTC by Ornella452

2021-06-24 18:39 UTC, squirrion commented on src/components/common/Header.js
> +                                        <Link to={'/prefet/mon-compte'}>Mon compte</Link>
@Ornella452 pas besoin je pense d'avoir une url différente entre admin et préfet si ?

2021-06-24 18:39 UTC, squirrion commented on src/components/common/Header.js
> +                              <span className="rf-fi-account-fill" /> {user?.name}
@Ornella452 du coup pour les structures pas de changement ?

2021-06-24 18:40 UTC, squirrion commented on src/components/connected/admin/index.js
> +            <Route path={`/prefet/mon-compte`} component={MonCompte} />
@Ornella452 à confirmer mais je pense pas qu'il y ait besoin de 2 routes différentes

2021-06-24 19:44 UTC, Ornella452 commented on src/components/common/Header.js
> +                              <span className="rf-fi-account-fill" /> {user?.name}
non pas de changement , car sur le ticket il est précisé que la fonctionnalité est pour les compte avec un role de admin et prefet

2021-06-24 19:51 UTC, Ornella452 commented on src/components/connected/admin/index.js
> +            <Route path={`/prefet/mon-compte`} component={MonCompte} />
peut être faire tout simplement : '/mon-compte' ?!

2021-06-25 10:15 UTC, Ornella452 commented on src/components/connected/admin/index.js
> +            <Route path={`/prefet/mon-compte`} component={MonCompte} />
yes tu as raison pas besoin d'en faire 2 :)

2021-06-25 15:58 UTC, squirrion commented on src/components/common/Header.js
> +                              <span className="rf-fi-account-fill" /> {user?.name}
@Ornella452 Ok ! le titre et le contenu du ticket divergent :) : "laisser l'utilisateur d'une SA changer son email" veut dire une structure !! A voir si faut l'ouvrir pour tous du coup !

2021-06-28 07:27 UTC, Ornella452 commented on src/components/common/Header.js
> +                              <span className="rf-fi-account-fill" /> {user?.name}
oui effectivement ça divergent ! il me semble que le détail à était mis à jour mais le titre je ne pense pas

2021-06-28 07:32 UTC, Ornella452 commented on src/components/common/Header.js
> +                              <span className="rf-fi-account-fill" /> {user?.name}
@squirrion je pense que c'est bon pour dans le titre, il est préciser l'email de connexion

2021-06-30 09:51 UTC, Ornella452 commented on src/components/common/Header.js
> +                              <span className="rf-fi-account-fill" /> {user?.name}
@squirrion tu avais raison pour l'ouverture à tous :)

2021-06-30 09:58 UTC, squirrion commented on src/actions/user.actions.js
> +  getUtilisateur
@Ornella452 getUser

2021-06-30 09:58 UTC, squirrion commented on src/actions/user.actions.js
> +function getUtilisateur(_id) {
@Ornella452 getUser

2021-06-30 10:03 UTC, squirrion commented on src/actions/user.actions.js
> +function patchUser(compte) {
@Ornella452 Si j'ai bien compris tu n'envoies pas l'objet user entier mais que id et un nouveau email saisi, tu peux mettre patchUser(id, newEmail)

2021-06-30 10:04 UTC, squirrion commented on src/actions/user.actions.js
> +    userService.patchUser(compte)
@Ornella452 idem donc

2021-06-30 10:07 UTC, loicguillois commented on src/actions/user.actions.js
> +function patchUser(compte) {
et du coup il faut être plus précis. ce serait plutôt `updateUserEmail` à la place de `patchUser`

2021-06-30 10:08 UTC, loicguillois commented on src/actions/user.actions.js
> +    return { type: 'PATCH_USER_REQUEST' };
pareil, `UPDATE_USER_EMAIL_REQUEST` et à changer aussi pour les autres

2021-06-30 10:08 UTC, loicguillois commented on src/components/connected/admin/MonCompte.js
> +  const userconnect = useSelector(state => state.user?.userId);
`connectedUser` (utilises le camel case)

2021-06-30 10:11 UTC, squirrion commented on src/actions/user.actions.js
> +    userService.getUtilisateur(_id)
@Ornella452 idem

2021-06-30 10:12 UTC, loicguillois commented on src/components/connected/admin/MonCompte.js
> +                  Veuillez entrez une autre adresse e-mail car il éxiste déjà dans une autre structure
`Cet adresse e-mail est déjà utilisée`

ça suffit 👍

2021-06-30 10:12 UTC, loicguillois commented on src/components/connected/structure/index.js
> +            <Route path={`/structure/mes-informations`} component={MesInformations} />
`/structure/informations`

2021-06-30 10:13 UTC, squirrion commented on src/components/common/Header.js
> +    await dispatch(userActions.getUtilisateur(connect?._id));
@Ornella452 await nécessaire ?

2021-06-30 10:14 UTC, squirrion commented on src/components/common/Header.js
> +  const connect = useSelector(state => state.authentication?.user?.user);
@Ornella452 ici ce serait plutot user

2021-06-30 10:15 UTC, squirrion commented on src/components/common/Header.js
> +  const user = useSelector(state => state?.user?.userId);
@Ornella452 Et ici userId non ?

2021-06-30 10:16 UTC, squirrion commented on src/components/connected/admin/MonCompte.js
> +    await dispatch(userActions.getUser(_id));
@Ornella452 pareil ca m'étonne l'asynchrone ici

2021-06-30 10:17 UTC, squirrion commented on src/components/connected/admin/MonCompte.js
> +  const userconnect = useSelector(state => state.user?.userId);
@Ornella452 Il y a 2 variables seSelector(state => state.user?.userId);  : user et userconnect.
J'aurais mis userId

2021-06-30 10:18 UTC, squirrion commented on src/components/connected/admin/MonCompte.js
> +                  Veuillez entrez une autre adresse e-mail car il éxiste déjà dans une autre structure
@Ornella452 existe sans é

2021-06-30 10:19 UTC, squirrion commented on src/components/connected/admin/MonCompte.js
> +              Modifier mon adresse e-mail &ensp;
@Ornella452 `&ensp;` ?

2021-06-30 10:20 UTC, squirrion commented on src/components/connected/admin/index.js
> +  useEffect(async () => {
@Ornella452 si pas de await pas de async

2021-06-30 10:21 UTC, Ornella452 commented on src/components/connected/admin/MonCompte.js
> +              Modifier mon adresse e-mail &ensp;
c'est pour faire un petit espace et à coter il y a le petit icone

2021-06-30 10:22 UTC, Ornella452 commented on src/components/connected/admin/MonCompte.js
> +                  Veuillez entrez une autre adresse e-mail car il éxiste déjà dans une autre structure
du coup pour le message Loïc m'a suggérer ça : ` Cet adresse e-mail est déjà utilisée`

2021-06-30 10:23 UTC, squirrion commented on src/services/user.service.js
> +  const requestOptions = {
@Ornella452 il manque pas le authHeader pour que ca passe?

2021-06-30 10:24 UTC, Ornella452 commented on src/components/common/Header.js
> +    await dispatch(userActions.getUtilisateur(connect?._id));
je ne pense pas au final car je l'avais mis un moment quand je n'arriver pas à récupérer les données, du coup oui je pense le retirer...

2021-06-30 10:25 UTC, squirrion commented on src/components/connected/admin/MonCompte.js
> +              Modifier mon adresse e-mail &ensp;
@Ornella452 Ok c'est pas plutot `&nbsp;` ?

2021-06-30 10:29 UTC, Ornella452 commented on src/services/user.service.js
> +  const requestOptions = {
effectivement j'ai oublier de l'ajouter ! mais il marche même sans

2021-06-30 11:02 UTC, squirrion commented on src/services/user.service.js
> +  const requestOptions = {
Hum c'est parce que le test doit être avec un user role admin sinon c'est non autorisé

2021-06-30 11:16 UTC, Ornella452 commented on src/components/connected/admin/MonCompte.js
> +  const userconnect = useSelector(state => state.user?.userId);
merci , tu a l'œil XD

2021-07-01 17:00 UTC, squirrion commented on src/components/common/Header.js
> +
@Ornella452 Ok juste vérifier avec un console.log('coucou') qu'il n'y a pas de boucle dans le use effect quand tu te navigues sur le backoffice

2021-07-01 22:08 UTC, Ornella452 commented on src/components/common/Header.js
> +
nop pas de boucle infini :)

2021-07-02 14:03 UTC, squirrion commented on src/components/common/Header.js
> +function Header(connected) {
@Ornella452 Il faut remettre { connected ] sinon connected vaudra { } par défaut et du coup  la condition` { connected &&` vaudra vrai tout le temps et donc le menu mon compte et le bouton déconnexion s'affichera même si user pas connecté

2021-07-02 14:06 UTC, squirrion commented on src/components/common/Header.js
> +                              <button className="rf-sidemenu__btn" aria-expanded="false" aria-controls="menu-776" aria-current="false">
@Ornella452 Pour régler ton souci de menu déroulant sans devoir recharger la page, il faut jouer avec le aria-expanded à true/false et ajouter/enlever la classe `rf-collapse--expanded` après `rf-collapse rf-nav--expanded` de la div du menu-776
Du coup, faut créer un useState pour ces 2 données et mettre un onClick sur le button pour faire jouer ces variables

2021-07-02 14:11 UTC, squirrion commented on src/components/common/Header.js
> +                              <button className="rf-sidemenu__btn" aria-expanded="false" aria-controls="menu-776" aria-current="false">
Tu pourras tester avant direct dans la console de ton navigateurs ca va fonctionner ;)

2021-07-02 14:13 UTC, Ornella452 commented on src/components/common/Header.js
> +function Header(connected) {
ha merci !! j'ai du le supprimer par erreur tellement que j'ai tester ^^'

2021-07-02 14:15 UTC, Ornella452 commented on src/components/common/Header.js
> +                              <button className="rf-sidemenu__btn" aria-expanded="false" aria-controls="menu-776" aria-current="false">
très bonne idée, je tente ...

2021-07-02 14:42 UTC, Ornella452 commented on src/components/common/Header.js
> +                              <button className="rf-sidemenu__btn" aria-expanded="false" aria-controls="menu-776" aria-current="false">
yes ça marche :)

2021-07-02 14:55 UTC, squirrion commented on src/components/common/Header.js
> +                              {menu === true ? <div className="rf-collapse--expanded" id="menu-776">
@Ornella452 Ok tu peux faire + simple pour la condition en un coup normalement : 
className={`rf-collapse rf-nav--expanded ${menu === true ? 'rf-collapse--expanded' : ''}`}>

2021-07-02 14:58 UTC, squirrion commented on src/components/common/Header.js
> +                              {menu === true ? <div className="rf-collapse--expanded" id="menu-776">
(avec le petit trait de travers altgr + chiffre 7) après { et avant }

2021-07-05 09:05 UTC, loicguillois requested changes

2021-07-05 09:05 UTC, loicguillois commented on src/actions/user.actions.js
> +    return { type: 'UPDATE_CONFIRME_USER_EMAIL_REQUEST' };
CONFIRMATION_UPDATE_USER_EMAIL_REQUEST

2021-07-05 09:05 UTC, loicguillois commented on src/actions/user.actions.js
> +    return { type: 'UPDATE_CONFIRME_USER_EMAIL_SUCCESS', user };
CONFIRMATION_UPDATE_USER_EMAIL_FAILURE

2021-07-05 09:14 UTC, loicguillois approved these changes

2021-07-05 09:16 UTC, merged

2021-07-05 21:36 UTC, squirrion commented on src/components/connected/admin/MonCompte.js
> +                  Cet adresse e-mail est déjà utilisée
@Ornella452 Normalement, on aurait pu mettre { error?.toString() } qui afficherait les messages en retour API notamment le 'Erreur: l\'email est déjà utilisé par une autre structure'