Ajouter une colonne avec l'information "candidat déjà recruté" lorsque le candidat est recruté
anct-cnum/portail-backoffice pull request #199
Opened 2021-07-23 13:30 UTC by Ornella452

…isponible

2021-07-23 13:37 UTC, squirrion commented on src/components/connected/structure/Conseiller.js
> +    key: 'finalisee_non_disponible',
@Ornella452 Du coup, les finalisee_non_disponible s'affichent que dans le filtre Toutes les candidatures si, c'est ben ça ? vu que ce n'est pas statut nouvelle ou interessee etc..

2021-07-23 13:42 UTC, Ornella452 commented on src/components/connected/structure/Conseiller.js
> +    key: 'finalisee_non_disponible',
oui c'est exacte !

2021-07-23 13:42 UTC, Ornella452 commented on src/components/connected/structure/Conseiller.js
> +    key: 'finalisee_non_disponible',
faut - il créer également un filtre dédier ?

2021-07-23 13:59 UTC, squirrion commented on src/components/connected/structure/Conseiller.js
> +    key: 'finalisee_non_disponible',
Je ne pense pas vu qu'ils ne sont pas dispos cc @loicguillois

2021-07-23 15:32 UTC, loicguillois commented on src/components/connected/structure/Conseiller.js
> +    key: 'finalisee_non_disponible',
non pas précisé sur le ticket ;)

2021-07-23 15:33 UTC, loicguillois requested changes
je ne vois pas la nouvelle colonne et je ne vois pas où tu grises le bouton

2021-07-27 10:27 UTC, squirrion commented
@Ornella452 Vu pour le design de Raphael : pas d'ajout de nouvelle colonne mais le nom du statut en déjà recruté visible donc uniquement dans "Afficher toutes les candidatures"
Il faudra donc renommer la PR

2021-07-27 12:21 UTC, squirrion requested changes
test de dismiss

2021-07-27 12:23 UTC, squirrion approved these changes

2021-07-27 13:51 UTC, squirrion commented
@Ornella452 Alors il y a une modif à faire dans le search (pour la création à la volée d'une mise en relation en type manuel). Il faut que dans le find pour une structure, on ne renvoie pas les conseillers qui sont "finalisee" avec une autre structure

2021-07-28 15:02 UTC, squirrion approved these changes

2021-07-28 16:26 UTC, jystervinou approved these changes

2021-07-29 08:51 UTC, merged