Ajout du filtre CV sur mes candidats
anct-cnum/portail-backoffice pull request #218
Opened 2021-08-11 12:43 UTC by MorganP-projects

2021-08-11 13:00 UTC, loicguillois requested changes

2021-08-11 13:00 UTC, loicguillois commented on src/components/connected/structure/FiltersAndSorts.js
> +    }
`cv = cv === 'true';` devrait suffire

2021-08-11 13:00 UTC, loicguillois commented on src/services/conseiller.service.js
> +    //CV ?
commentaire pas utile, sinon créer une fonction `haveCV` par exemple pour y mettre la vérification `persoFilters?.cv !== undefined && persoFilters?.cv !== ''`

2021-08-11 13:00 UTC, loicguillois commented on src/components/connected/structure/FiltersAndSorts.js
> +    let cv = document.getElementById('selectCV').value;
à bannir ! on utilise le state, d'autant que tu as mis en place le callback `changeCV`

2021-08-11 13:16 UTC, MorganP-projects commented on src/components/connected/structure/FiltersAndSorts.js
> +    let cv = document.getElementById('selectCV').value;
Ok ! Je vais faire la modif sur les autres filtres également du coup !

2021-08-12 07:56 UTC, squirrion approved these changes

2021-08-12 08:47 UTC, loicguillois approved these changes

2021-08-12 08:50 UTC, merged