Revoir wording candidats "déjà recrutés" sur l'espace admin
anct-cnum/portail-backoffice pull request #232
Opened 2021-08-27 09:33 UTC by Ornella452

2021-08-30 07:36 UTC, loicguillois approved these changes

2021-08-30 12:53 UTC, squirrion commented
@Ornella452 Ok du coup il faudrait revoir cet ordre dans le front ?

2021-08-31 07:26 UTC, squirrion requested changes
Je regarderai pour l'ordre d'affichage du coup

2021-08-31 14:05 UTC, squirrion approved these changes

2021-08-31 14:19 UTC, MorganP-projects approved these changes

2021-08-31 15:05 UTC, loicguillois approved these changes

2021-08-31 15:06 UTC, merged