Invitation espace candidat
anct-cnum/portail-backoffice pull request #283
Opened 2021-11-08 16:44 UTC by Ornella452

2021-11-08 17:37 UTC, squirrion commented on src/components/connected/admin/ConseillerDetails.js
> +          {/* L&rsquo;envoi du mail de relance d&rsquo;inscription a échoué, veuillez réessayer plus tard */}
@Ornella452 comm à supprimer ?

2021-11-08 17:43 UTC, squirrion requested changes

2021-11-08 17:43 UTC, squirrion commented on src/components/connected/admin/ConseillerDetails.js
> +              Renvoyer l&rsquo;email d&rsquo;inscription [Espace candidat]</button>
@Ornella452 Indentation

2021-11-08 17:43 UTC, squirrion commented on src/reducers/conseillerReducer.js
> +        flashMessage: false,
@Ornella452 je pense que tu pouvais jouer avec loadingInviteCandidat sans passer un autre paramètre flashMessage

2021-11-08 17:43 UTC, squirrion commented on src/reducers/conseillerReducer.js
> +        flashMessage: false,
@Ornella452 reseter le errorResendInscriptionCandidat

2021-11-09 10:06 UTC, Ornella452 commented on src/components/connected/admin/ConseillerDetails.js
> +          {/* L&rsquo;envoi du mail de relance d&rsquo;inscription a échoué, veuillez réessayer plus tard */}
👍 oui oublier

2021-11-09 14:12 UTC, Ornella452 commented on src/reducers/conseillerReducer.js
> +        flashMessage: false,
vu avec seb, on laisse comme ça 👍

2021-11-09 15:49 UTC, loicguillois commented on src/components/connected/admin/ConseillerDetails.js
> +  const sucessSendMail = useSelector(state => state.conseiller?.sucessResendInscriptionCandidat);
`successSendMail`

2021-11-09 15:55 UTC, Ornella452 commented on src/components/connected/admin/ConseillerDetails.js
> +  const sucessSendMail = useSelector(state => state.conseiller?.sucessResendInscriptionCandidat);
oh bien vue !!

2021-11-09 16:09 UTC, loicguillois approved these changes

2021-11-09 16:23 UTC, Ornella452 commented on src/components/connected/admin/ConseillerDetails.js
> +            visible={invitCandidat?.loadingInviteCandidat === true}
@loicguillois   c'est seulement une faute de ma part , il y a pas de raison particulière !
préfère tu avec un e ou sans e ?
(je ferai la modif pour la cohérence)

2021-11-09 17:18 UTC, loicguillois commented on src/components/connected/admin/ConseillerDetails.js
> +  const successSendMail = useSelector(state => state.conseiller?.sucessResendInscriptionCandidat);
toujours pas:

`successResendInscriptionCandidat`

2021-11-09 17:20 UTC, loicguillois commented on src/components/connected/admin/ConseillerDetails.js
> +          Le mail de relance d&rsquo;inscription a bien été envoyé à {conseiller?.prenom}&nbsp;{conseiller?.nom}
`L'email`

2021-11-09 19:20 UTC, squirrion commented on src/components/connected/admin/ConseillerDetails.js
> +                  Renvoyer l&rsquo;email d&rsquo;inscription [Espace candidat]</button>
@Ornella452 Normal le [Espace candidat] en label ? (Renvoyer l&rsquo;email d&rsquo;inscription au candidat)

2021-11-09 19:24 UTC, squirrion commented on src/components/connected/admin/ConseillerDetails.js
> +        { (errorSendMail === undefined || successSendMail === true) &&
@Ornella452 errorSendMail peut valoir false (errorResendInscriptionCandidat: false dans le reducer)

2021-11-09 19:24 UTC, squirrion commented on src/components/connected/admin/ConseillerDetails.js
> +        { (errorSendMail !== undefined && successSendMail === undefined) &&
@Ornella452 idem

2021-11-09 19:24 UTC, squirrion commented on src/components/connected/admin/ConseillerDetails.js
>                <div>
@Ornella452 indentation de la fin de div

2021-11-10 10:56 UTC, Ornella452 commented on src/components/connected/admin/ConseillerDetails.js
> +                  Renvoyer l&rsquo;email d&rsquo;inscription [Espace candidat]</button>
vu avec seb

2021-11-10 13:20 UTC, squirrion approved these changes

2021-11-10 13:21 UTC, merged