modifications suite recette
anct-cnum/portail-backoffice pull request #34
Opened 2021-02-18 17:04 UTC by squirrion

2021-02-18 17:10 UTC, loicguillois requested changes

2021-02-18 17:10 UTC, loicguillois commented on src/components/connected/structure/Conseiller.js
> +          miseEnRelationDistance: distance }}>
faudrait passer l'objet `miseEnrelation` directement ça éviterait d'avoir trop de paramètres

2021-02-18 17:10 UTC, loicguillois commented on src/components/connected/structure/ConseillerDetails.js
> +  let conseillerId = location.pathname.substring(location.pathname.lastIndexOf('/') + 1);
pourquoi tu n'utilises pas `useParams` ?

2021-02-18 17:10 UTC, loicguillois commented on src/components/connected/structure/ConseillerDetails.js
> +        <p>Distance de déplacement : {Math.round(location.miseEnRelationDistance)}&nbsp;Km</p>
ce sont des mètres non ? utilises plutôt des littéraux pour la mise en forme : `{`${location.miseEnRelationDistance} km`}`

2021-02-18 17:12 UTC, squirrion commented on src/components/connected/structure/ConseillerDetails.js
> +  let conseillerId = location.pathname.substring(location.pathname.lastIndexOf('/') + 1);
@loicguillois il n'est présent que dans l'url (dans le path), il ne l'est plus dans params côté Link
Ou alors on le rajouter dans le Link

2021-02-18 19:07 UTC, squirrion commented on src/components/connected/structure/Conseiller.js
> +          miseEnRelationDistance: distance }}>
@loicguillois OK j'ai modifié en passant la miseEnRelation directe comme on a besoin du conseiller et des autres champs (statut, distance, id)

2021-02-18 19:07 UTC, squirrion commented on src/components/connected/structure/ConseillerDetails.js
> +  let conseillerId = location.pathname.substring(location.pathname.lastIndexOf('/') + 1);
@loicguillois OK comme vu ensemble c'est plutot let { id } = useParams();

2021-02-18 19:08 UTC, squirrion commented on src/components/connected/structure/ConseillerDetails.js
> +        <p>Distance de déplacement : {Math.round(location.miseEnRelationDistance)}&nbsp;Km</p>
@loicguillois Oui j'avais été trop vite... j'ai modifié en { Math.ceil(location.miseEnRelation?.distance / 1000)}&nbsp;Km
Conversion de m en Km avec arrondi supérieur

2021-02-18 19:15 UTC, squirrion commented
@loicguillois J'ai ajouté la ternaire pour le telephone : {conseiller?.conseiller?.telephone ? conseiller?.conseiller?.telephone : 'pas de numéro de téléphone' }

2021-02-22 13:33 UTC, loicguillois approved these changes

2021-02-22 13:45 UTC, merged