Afficher les infos Si compte candidat Activé oui ou non
anct-cnum/portail-backoffice pull request #346
Opened 2022-05-25 14:52 UTC by QuentinFontenay

2022-05-27 14:20 UTC, squirrion commented on src/components/connected/admin/ConseillerDetails.js
> +              {(!conseiller?.estRecrute && role === 'admin') &&
ok ou sur le statut !== 'RECRUTE'

2022-05-30 10:39 UTC, MorganP-projects approved these changes

2022-05-30 14:49 UTC, Ornella452 approved these changes

2022-05-30 18:45 UTC, squirrion commented on src/components/connected/admin/ConseillerDetails.js
> +                  <p>Posséde un compte candidat : {conseiller?.possedeCompteCandidat ? 'Oui' : 'Non'}</p>
possède

2022-05-30 18:45 UTC, squirrion commented on src/components/connected/admin/ConseillerDetails.js
> +                  <p>Posséde un compte candidat : {conseiller?.possedeCompteCandidat ? 'Oui' : 'Non'}</p>
```suggestion
                  <p>Possède un compte candidat&nbsp;: {conseiller?.possedeCompteCandidat ? 'Oui' : 'Non'}</p>
```

2022-05-30 18:45 UTC, squirrion commented on src/components/connected/admin/ConseillerDetails.js
> +                  <p>Posséde un compte candidat : {conseiller?.possedeCompteCandidat ? 'Oui' : 'Non'}</p>
```suggestion
                  <p>Possède un compte candidat&nbsp;: {conseiller?.possedeCompteCandidat ? 'Oui' : 'Non'}</p>
```

2022-05-30 18:47 UTC, squirrion requested changes
Petit comm

2022-05-31 10:50 UTC, squirrion approved these changes

2022-05-31 12:24 UTC, merged